language: python
python:
  - 3.4
  
install:
  - pip install -r requirements.txt
  - pip install coveralls
 
script:
  - cd testing
  - coverage run --source=../pytrade -m pytest

after_success:
  coveralls
